export const submitText = 'Finalizar';
export const submittingText = 'Enviando';
export const loading = 'Cargando';
export const welcome = 'Bienvenido';
export const description = 'Escoge una opción para cada pregunta';
export const surveyFinished = 'Encuesta finalizada';
export const goBack = 'Volver';
export const exit = 'Salir';
export const errorlabel = 'Hubo un error en el servicio.';
